### ISSUE TITLE
NoSuchMethodError in CloudFoundryServiceInfoCreator

### ISSUE THREAD

**Issue by royclarkson** [pivotal-cf/spring-cloud-pivotal-connector#1]
I'm seeing this exception with a very basic app. It works locally when connecting to a local Spring Cloud Config Server, but when I add the spring-cloud-pivotal-connector dependency to the POM, it throws this exception.

Here is the code with which I'm working:
https://github.com/pcf-guides/gs-configuration-server/tree/master/complete

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.boot.maven.RunMojo$LaunchRunner.run(RunMojo.java:418)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ServiceConfigurationError: org.springframework.cloud.CloudConnector: Provider org.springframework.cloud.cloudfoundry.CloudFoundryConnector could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.springframework.cloud.CloudFactory.scanCloudConnectors(CloudFactory.java:91)
	at org.springframework.cloud.CloudFactory.<init>(CloudFactory.java:35)
	at org.springframework.cloud.pcf.configserver.ConfigServerServiceConnector.onApplicationEvent(ConfigServerServiceConnector.java:32)
	at org.springframework.cloud.pcf.configserver.ConfigServerServiceConnector.onApplicationEvent(ConfigServerServiceConnector.java:19)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:100)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:59)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:286)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:961)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:950)
	at demo.Application.main(Application.java:10)
	... 6 more
Caused by: java.util.ServiceConfigurationError: org.springframework.cloud.cloudfoundry.CloudFoundryServiceInfoCreator: Provider org.springframework.cloud.pcf.phd.PhdServiceInfoCreator could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.springframework.cloud.AbstractCloudConnector.scanServiceInfoCreators(AbstractCloudConnector.java:53)
	at org.springframework.cloud.AbstractCloudConnector.<init>(AbstractCloudConnector.java:33)
	at org.springframework.cloud.cloudfoundry.CloudFoundryConnector.<init>(CloudFoundryConnector.java:32)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:438)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 20 more
Caused by: java.lang.NoSuchMethodError: org.springframework.cloud.cloudfoundry.CloudFoundryServiceInfoCreator.<init>(Lorg/springframework/cloud/cloudfoundry/Tags;[Ljava/lang/String;)V
	at org.springframework.cloud.pcf.phd.PhdServiceInfoCreator.<init>(PhdServiceInfoCreator.java:22)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:438)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 31 more
```

**Comment by royclarkson** [comment]
The latest snapshot of `spring-cloud-pivotal-connector` requires a newer version of `spring-cloud-cloudfoundry-connector` than is in `spring-cloud-starter-parent` 1.0.0.RC1. Explicitly including the newer version resolves this exception.
